### ISSUE TITLE
Incompatible with new version of Ocelot

### ISSUE THREAD

**Issue by szakula-hinda** [Burgyn/MMLib.Ocelot.Provider.AppConfiguration#7]
**Describe the bug**
This library is incompatible with Ocelot version 20 because they renamed the "Get" method to "GetAsync" in IServiceDiscoveryProvider. 

**Expected behavior**
A new version of this library is needed that renames to GetAsync and references the updated interface definition.

**To Reproduce**
Update ocelot package to version 20.

**Comment by Burgyn** [comment]
Hi @szakula-hinda,

thanks for your issue. This is fixed in version `3.0.0` an will be release in a few minutes.
